### ISSUE TITLE
Can't change TransLogger format

### ISSUE THREAD

**Issue by ariksa** [cdent/paste#63]
It seems it is impossible to really change the TransLogger format. I can initiate the class it like this:
`TransLogger(app, format=MY_FORMAT)`
But MY_FORMAT **really** needs to align with the default one, otherwise it fails in
`paste/translogger.py", line 99`

**Comment by cdent** [comment]
Can you provide the `MY_FORMAT` that you are using that fails, and the traceback that happens when it fails? Without that it's hard to narrow down the issue.

**Comment by ariksa** [comment]
I wanted to go with standard logging format:
`MY_FORMAT = '[%(levelname)s] (%(filename)s:%(lineno)d) - %(message)s'`
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/waitress/channel.py", line 356, in service
    task.service()
  File "/usr/lib/python3.6/site-packages/waitress/task.py", line 176, in service
    self.execute()
  File "/usr/lib/python3.6/site-packages/waitress/task.py", line 447, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/usr/lib/python3.6/site-packages/paste/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "/usr/lib/python3.6/site-packages/connexion/apps/abstract.py", line 248, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2318, in wsgi_app
    return response(environ, start_response)
  File "/usr/lib/python3.6/site-packages/werkzeug/wrappers/base_response.py", line 701, in __call__
    start_response(status, headers)
  File "/usr/lib/python3.6/site-packages/paste/translogger.py", line 67, in replacement_start_response
    self.write_log(environ, method, req_uri, start, status, bytes)
  File "/usr/lib/python3.6/site-packages/paste/translogger.py", line 99, in write_log
    message = self.format % d
KeyError: 'levelname'
```

**Comment by cdent** [comment]
Ah, okay. As you've probably already determined, there is a defined set of variables that you can provide, using Translogger, the left hand side in this dict:

```python
        d = {                                                                   
            'REMOTE_ADDR': remote_addr,                                         
            'REMOTE_USER': environ.get('REMOTE_USER') or '-',                   
            'REQUEST_METHOD': method,                                           
            'REQUEST_URI': req_uri,                                             
            'HTTP_VERSION': environ.get('SERVER_PROTOCOL'),                     
            'time': time.strftime('%d/%b/%Y:%H:%M:%S ', start) + offset,        
            'status': status.split(None, 1)[0],                                 
            'bytes': bytes,                                                     
            'HTTP_REFERER': environ.get('HTTP_REFERER', '-'),                   
            'HTTP_USER_AGENT': environ.get('HTTP_USER_AGENT', '-'),             
            }                                        
```

To get the output that you want you're probably better off using either a different logging middleware, or a subclass of Translogger.

In any case, given that paste is in maintenance mode, and the code is behaving as designed (setting aside for the moment whether that design is good), this is not something that's going to change.

I'm not certain, but I suspect either waitress or flask should be able to provide you with different modes of logging that could fit your needs.

If all that makes sense, please close the issue.

**Comment by ariksa** [comment]
You are right, I saw that dictionary and hence opened this issue.
But I can't fight maintenance mode :)
Thanks, closing.
