### ISSUE TITLE
Paste 3.0.0 breaks PasteScript 1.7.5

### ISSUE THREAD

**Issue by bszonye** [cdent/paste#7]
I’m supporting some applications using an older version of Paste & PasteScript (1.7.5) and after the Paste 3.0.0 release, we can no longer install PasteScript from a requirements.txt file or on a single command line.
```
$ pip install Paste==1.7.5.1 PasteScript==1.7.5
```
with:
```
pip        18.1
setuptools 40.4.3
virtualenv 16.0.0
```
hits a maximum recursion depth after several minutes, while running setup.py for indirect dependency future-0.16.0:
```
    Running future-0.16.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-J2tkub/future-0.16.0/egg-dist-tmp-CdWQdD
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-J2tkub/future-0.16.0/temp/easy_install-FpZEOa/future-0.16.0/temp/easy_install-tNYhgF/future-0.16.0/temp/easy_install-6FBafq/future-0.16.0/temp/easy_install-8E2U5i/future-0.16.0/temp/easy_install-F7xFsH/future-0.16.0/temp/easy_install-S0Urui/future-0.16.0/setup.py", line 186, in <module>
...
      File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 419, in _open
        return _open(path, mode, *args, **kw)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 419, in _open
        return _open(path, mode, *args, **kw)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 417, in _open
        if mode not in ('r', 'rt', 'rb', 'rU', 'U') and not self._ok(path):
    RuntimeError: maximum recursion depth exceeded in cmp
```

PasteScript>=2 installs ok, but I don’t know whether it’s sufficiently compatible with our applications.

**Comment by cdent** [comment]
#6 looks like a slightly more concise version of the same problem, so I'll be working this over there. Thanks very much for the quick report, this kind of quick feedback was what I was hoping for by releasing things.
